import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import { useMount } from '../app/foundation/useMount'
import IndexPage from '../app/components/Home'
import { mount, register } from 'lake'

const Home: NextPage = () => {
  const refContainer = useRef<HTMLDivElement | null>(null)

  useMount(() => {
    register('Index', IndexPage)
    mount(refContainer.current!, {}, 'Index')
  })

  return (
    <div id="root" ref={refContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="gl" className="fixed inset-0"></div>

      <main className="">
        <section className="projects"></section>
        <section className="about"></section>
      </main>
    </div>
  )
}

export default Home
