import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import { useMount } from '../app/foundation/useMount'
import IndexPage from '../app/components/Home'
import { mount, register, unmount as __ } from 'lake'

const Home: NextPage = () => {
  const refContainer = useRef<HTMLDivElement | null>(null)

  useMount(() => {
    register('Index', IndexPage)
    mount(refContainer.current!, {}, 'Index')

    return () => {
      console.log('unmount')
    }
  })

  return (
    <div className="" ref={refContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=""></main>

      <footer className="">
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </footer>
    </div>
  )
}

export default Home
